"""Change token-user relationship

Revision ID: 9150563ed64f
Revises: dc3022f9a59e
Create Date: 2022-07-01 11:23:09.277917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9150563ed64f'
down_revision = 'dc3022f9a59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
